#!/usr/bin/env python3
"""
report_generator.py — JSON Security Report Generator.

Produces structured JSON reports containing all scan, analysis, and
detection results.  Also provides a human-readable terminal summary.
"""

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from src.utils import get_reports_dir

logger = logging.getLogger("cli_network_scanner.report_generator")


def generate_report(
    network_info: dict[str, Any],
    scan_results: dict[str, Any],
    process_mappings: list[dict[str, Any]],
    packet_analysis: dict[str, Any],
    classifications: list[dict[str, Any]],
    detection_summary: dict[str, Any],
    lab_services: list[dict[str, Any]],
    capture_info: dict[str, Any],
    traffic_results: dict[str, Any],
    target: str = "127.0.0.1",
    errors: Optional[list[str]] = None,
) -> dict[str, Any]:
    """Build the complete security report.

    Args:
        network_info: From network_info.get_all_network_info().
        scan_results: From port_scanner.run_nmap_scan().
        process_mappings: From process_mapper.map_ports_to_processes().
        packet_analysis: From packet_analyzer.analyze_capture().
        classifications: From suspicious_ports.classify_ports().
        detection_summary: From suspicious_ports.get_detection_summary().
        lab_services: From lab_server.LabEnvironment.get_services_info().
        capture_info: From packet_capture.PacketCapture.get_capture_info().
        traffic_results: From traffic_generator.generate_all_traffic().
        target: The scan target IP.
        errors: Any errors encountered during the run.

    Returns:
        The complete report dictionary.
    """
    report: dict[str, Any] = {
        "scan_metadata": {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "target": target,
            "authorized_lab": True,
            "tool": "CLI Network Scanner + Packet Analyzer",
            "version": "1.0.0",
        },
        "host": {
            "hostname": network_info.get("hostname", ""),
            "local_ip": network_info.get("local_ip", ""),
            "loopback": network_info.get("loopback", "127.0.0.1"),
            "interface": network_info.get("interface", ""),
            "default_gateway": network_info.get("default_gateway", ""),
        },
        "open_ports": [
            p for p in scan_results.get("ports", [])
            if p.get("state") == "open"
        ],
        "all_ports": scan_results.get("ports", []),
        "process_mapping": _sanitize_process_mappings(process_mappings),
        "packet_statistics": _sanitize_packet_analysis(packet_analysis),
        "traffic_generation": {
            "total_requests": traffic_results.get("total_success", 0),
            "total_errors": traffic_results.get("total_errors", 0),
        },
        "suspicious_ports": classifications,
        "detection_summary": detection_summary,
        "lab_services": lab_services,
        "capture_file": capture_info.get("capture_file", ""),
        "scan_info": scan_results.get("scan_info", {}),
        "errors": errors or [],
        "disclaimer": (
            "This report is generated by an educational security tool. "
            "An open port does NOT prove that a service is vulnerable or "
            "malicious. All findings should be interpreted in context. "
            "This tool is designed for authorized local lab use only."
        ),
    }

    logger.info("Report generated with %d open ports", len(report["open_ports"]))
    return report


# Use Optional from typing for compatibility
from typing import Optional


def _sanitize_process_mappings(
    mappings: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Ensure process mappings are JSON-serializable.

    Args:
        mappings: Raw process mappings.

    Returns:
        Cleaned mappings.
    """
    clean: list[dict[str, Any]] = []
    for m in mappings:
        clean.append({
            "port": m.get("port"),
            "protocol": m.get("protocol", "tcp"),
            "pid": m.get("pid"),
            "process_name": str(m.get("process_name", "")),
            "cmdline": str(m.get("cmdline", "")),
        })
    return clean


def _sanitize_packet_analysis(analysis: dict[str, Any]) -> dict[str, Any]:
    """Ensure packet analysis data is JSON-serializable.

    Args:
        analysis: Raw analysis data.

    Returns:
        Cleaned analysis data.
    """
    # Most data should already be serializable; ensure Counter objects are dicts
    sanitized = {}
    for key, value in analysis.items():
        if hasattr(value, "items") and not isinstance(value, dict):
            sanitized[key] = dict(value)
        else:
            sanitized[key] = value
    return sanitized


def save_report(report: dict[str, Any], filename: str = "") -> str:
    """Save the report as JSON.

    Args:
        report: The complete report dictionary.
        filename: Optional override filename.

    Returns:
        Path to the saved report file.
    """
    reports_dir = get_reports_dir()

    if filename:
        report_path = reports_dir / filename
    else:
        # Timestamped filename
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        report_path = reports_dir / f"network_scan_report_{ts}.json"

    try:
        with open(report_path, "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2, default=str, ensure_ascii=False)

        # Also save a "latest" copy
        latest_path = reports_dir / "network_scan_report.json"
        with open(latest_path, "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2, default=str, ensure_ascii=False)

        logger.info("Report saved to %s", report_path)
        return str(report_path)

    except (OSError, TypeError) as exc:
        logger.error("Failed to save report: %s", exc)
        return ""


def print_report_summary(report: dict[str, Any]) -> None:
    """Print a concise terminal summary of the report.

    Args:
        report: The complete report dictionary.
    """
    print("\n" + "=" * 52)
    print("  SCAN REPORT SUMMARY")
    print("=" * 52)

    # Host info
    host = report.get("host", {})
    print(f"\n  Host       : {host.get('hostname', 'N/A')}")
    print(f"  Local IP   : {host.get('local_ip', 'N/A')}")
    print(f"  Target     : {report.get('scan_metadata', {}).get('target', 'N/A')}")

    # Open ports
    open_ports = report.get("open_ports", [])
    print(f"\n  Open ports : {len(open_ports)}")
    for p in open_ports:
        print(f"    {p['port']}/{p['protocol']} - {p.get('service', 'unknown')}")

    # Detection summary
    det = report.get("detection_summary", {})
    counts = det.get("counts", {})
    print(f"\n  Detection results:")
    print(f"    EXPECTED : {counts.get('EXPECTED', 0)}")
    print(f"    UNKNOWN  : {counts.get('UNKNOWN', 0)}")
    print(f"    REVIEW   : {counts.get('REVIEW', 0)}")
    print(f"    Risk     : {det.get('risk_level', 'N/A')}")

    # Packet stats
    pkt = report.get("packet_statistics", {})
    print(f"\n  Packets    : {pkt.get('total_packets', 0)}")

    # Report file
    meta = report.get("scan_metadata", {})
    print(f"\n  Timestamp  : {meta.get('timestamp', 'N/A')}")
    print(f"  Capture    : {report.get('capture_file', 'N/A')}")

    # Disclaimer
    print(f"\n  NOTE: {report.get('disclaimer', '')[:80]}...")

    # Errors
    errors = report.get("errors", [])
    if errors:
        print(f"\n  Warnings/Errors ({len(errors)}):")
        for e in errors[:5]:
            print(f"    [!] {e}")

    print("=" * 52)
